SELECT        TOP (200) DATA_NO, INPUT_DATE, SHEET_DATE, I_O_DV, DATA_DV, CONT_PLACE, IN_OUT_PLACE, ITEM_CODE, MOTHER_CODE, QUANTITY, PRICE, AMOUNT_PRICE, PRICE_UNIT, MEMO, LOT_NO, BOX_NO, INPUT_PERSON,
                          C_ORDER_NO, ORDER_NO, ORDER_SEQ, WAY, SHINGANE_TYPE, QUALITY_PASS, INSP_DATE, INSP_MAN, PRINT_DV, SHEET_NO, CHECK_SAMPLE, SHOW_DV, INV_DV, SHIP_TO, PALLET_NO, EXPIRE_DATE, 
                         DLVPRODF_ID, SO_TO_KHAI, END_CUSTOMER, OLD_QTY
FROM            IODATADF
WHERE        (LOT_NO LIKE '210218') AND (ITEM_CODE LIKE 'R1Z141A')